### ISSUE TITLE
Error compile

### ISSUE THREAD

**Issue by joaodh92** [urjaman/frser-atmega88#1]
Hello, i have an error when i try compile.
"h.c libfrser/frser.c libfrser/udelay.c
In function ‘__vector_19’:
uart.c:43:1: error: ‘_vector_19’ appears to be a misspelled signal handler [-Werror]
 ISR(USART_UDRE_vect) {
 ^
In function ‘__vector_18’:
uart.c:35:1: error: ‘_vector_18’ appears to be a misspelled signal handler [-Werror]
 ISR(USART_RX_vect) {
 ^
lto1: all warnings being treated as errors"

It is possible compile this project for atmega328?

**Comment by urjaman** [comment]
That false warning is given by the arduino toolchain iirc. Try to use something better, but it should build and maybe even work... if i hadnt forgotten some -Werror in there. Dropped that.
